#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cashflow9000.Resource", IsApplication=true)]

namespace Cashflow9000
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050015
			public const int buttonAdd = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int buttonBudgets = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int buttonCategories = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int buttonMilestone = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int buttonPlannedTransactions = 2131034131;
			
			// aapt resource value: 0x7f050001
			public const int buttonSave = 2131034113;
			
			// aapt resource value: 0x7f05000f
			public const int buttonTransaction = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int container = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int containerItem = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int containerList = 2131034125;
			
			// aapt resource value: 0x7f050005
			public const int editAmount = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int editName = 2131034115;
			
			// aapt resource value: 0x7f05001e
			public const int editNote = 2131034142;
			
			// aapt resource value: 0x7f050019
			public const int editValue = 2131034137;
			
			// aapt resource value: 0x7f05000a
			public const int gridLayout1 = 2131034122;
			
			// aapt resource value: 0x7f050016
			public const int listView = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int scrollView1 = 2131034136;
			
			// aapt resource value: 0x7f050007
			public const int spinCategory = 2131034119;
			
			// aapt resource value: 0x7f05001b
			public const int spinMilestone = 2131034139;
			
			// aapt resource value: 0x7f050009
			public const int spinRecurrence = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int spinType = 2131034123;
			
			// aapt resource value: 0x7f05001d
			public const int textDate = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int textRecurrence = 2131034140;
			
			// aapt resource value: 0x7f050014
			public const int textTitle = 2131034132;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int textView2 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int textView3 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int textView4 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int textView5 = 2131034120;
			
			// aapt resource value: 0x7f05001a
			public const int toggleType = 2131034138;
			
			// aapt resource value: 0x7f050017
			public const int toolbar = 2131034135;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Budget = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Category = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ItemActivity = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ListActivity = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Main = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Milestone = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ModelList = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Toolbar = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Transaction = 2130837512;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030013
			public const int add = 2130903059;
			
			// aapt resource value: 0x7f03000a
			public const int amount = 2130903050;
			
			// aapt resource value: 0x7f030012
			public const int annually = 2130903058;
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f03000f
			public const int biweekly = 2130903055;
			
			// aapt resource value: 0x7f030003
			public const int budget = 2130903043;
			
			// aapt resource value: 0x7f030002
			public const int category = 2130903042;
			
			// aapt resource value: 0x7f03000d
			public const int daily = 2130903053;
			
			// aapt resource value: 0x7f030015
			public const int date = 2130903061;
			
			// aapt resource value: 0x7f030005
			public const int expense = 2130903045;
			
			// aapt resource value: 0x7f030004
			public const int income = 2130903044;
			
			// aapt resource value: 0x7f030008
			public const int milestone = 2130903048;
			
			// aapt resource value: 0x7f030010
			public const int monthly = 2130903056;
			
			// aapt resource value: 0x7f030009
			public const int name = 2130903049;
			
			// aapt resource value: 0x7f03000c
			public const int none = 2130903052;
			
			// aapt resource value: 0x7f030007
			public const int note = 2130903047;
			
			// aapt resource value: 0x7f030016
			public const int plannedTransaction = 2130903062;
			
			// aapt resource value: 0x7f030011
			public const int quarterly = 2130903057;
			
			// aapt resource value: 0x7f03000b
			public const int recurrence = 2130903051;
			
			// aapt resource value: 0x7f030006
			public const int save = 2130903046;
			
			// aapt resource value: 0x7f030001
			public const int transaction = 2130903041;
			
			// aapt resource value: 0x7f030014
			public const int type = 2130903060;
			
			// aapt resource value: 0x7f03000e
			public const int weekly = 2130903054;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int MyTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
