#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cashflow9000.Resource", IsApplication=true)]

namespace Cashflow9000
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040002
			public const int buttonCategories = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int buttonMilestone = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int buttonSave = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int buttonTransaction = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int editAmount = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int editName = 2130968582;
			
			// aapt resource value: 0x7f04000f
			public const int editNote = 2130968591;
			
			// aapt resource value: 0x7f040009
			public const int editValue = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int spinCategory = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int spinMilestone = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int spinRecurrence = 2130968590;
			
			// aapt resource value: 0x7f040003
			public const int textView1 = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int textView2 = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int textView3 = 2130968583;
			
			// aapt resource value: 0x7f04000c
			public const int textView4 = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int toggleType = 2130968586;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Milestone = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Transaction = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030009
			public const int amount = 2130903049;
			
			// aapt resource value: 0x7f030010
			public const int annually = 2130903056;
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f03000d
			public const int biweekly = 2130903053;
			
			// aapt resource value: 0x7f030002
			public const int category = 2130903042;
			
			// aapt resource value: 0x7f03000b
			public const int daily = 2130903051;
			
			// aapt resource value: 0x7f030004
			public const int expense = 2130903044;
			
			// aapt resource value: 0x7f030003
			public const int income = 2130903043;
			
			// aapt resource value: 0x7f030007
			public const int milestone = 2130903047;
			
			// aapt resource value: 0x7f03000e
			public const int monthly = 2130903054;
			
			// aapt resource value: 0x7f030008
			public const int name = 2130903048;
			
			// aapt resource value: 0x7f030006
			public const int note = 2130903046;
			
			// aapt resource value: 0x7f03000f
			public const int quarterly = 2130903055;
			
			// aapt resource value: 0x7f03000a
			public const int recurrence = 2130903050;
			
			// aapt resource value: 0x7f030005
			public const int save = 2130903045;
			
			// aapt resource value: 0x7f030001
			public const int transaction = 2130903041;
			
			// aapt resource value: 0x7f03000c
			public const int weekly = 2130903052;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
